.\" Manpage for extmc
.\" Contact Yuuta Liang <yuuta@yuuta.moe> for typos.
.TH man 1 "15 May 2021" "1.0" "extmc manual page"
.SH NAME
extmc \- extmc daemon
.SH
SYNOPSIS
exmtc <path/to/autoloading/plugins>
.SH DESCRIPTION
A framework that reads the console output of Minecraft servers and deliver messages to plugins. extmc also provides rcon client APIs.
.SH AUTHOR
Written by Yuuta Liang <yuuta@yuuta.moe>.
.SH KNOWN BUGS
No known bugs.
Report bugs at https://github.com/YuutaW-Minecraft/extmc.
.SH SEE ALSO
extmcctl(1)
